export const AUTHORS_REQUEST = 'AUTHORS_REQUEST';
export const AUTHORS_SUCCESS = 'AUTHORS_SUCCESS';
export const AUTHORS_ERROR = 'AUTHORS_ERROR';
export const ADD_AUTHOR = 'ADD_AUTHOR';
export const DELETE_AUTHOR = 'DELETE_AUTHOR';
export const EDIT_AUTHOR = 'EDIT_AUTHOR';
